### Rocket Capital Investment Competition score & reward verification notebook
- The objective of this notebook is to provide clarity about the methodology of score & reward calculation.
- Please refer to https://rocket-capital-investment.gitbook.io/rci-competition/scoring-and-reward-policy for detail documentation.

In [1]:
# import libraries

import pandas as pd
import lib.validation as val

from lib.rocket import get_rocket_competition

#### To start, we define the challenge number that we want to verify the score & reward, it then query the Polygon blockchain to get the participant address

In [2]:
CHALLENGE_NUMBER = 2

# get competition, challenge and participants

competition = get_rocket_competition()
challenge = competition.get_challenge(CHALLENGE_NUMBER)
participants = challenge.get_all_participants()

# get participant addresses and build dataframe

addresses = [participant.address for participant in participants]
df = pd.DataFrame()
df["address"] = addresses
df.head()

scanning the Polygon blockchain
.....................................................................................................................................................................................................................................................................................................................................................................................................................................................................
blockchain scan completed

                                    address
0  16391fe372c2f5b2a3874e65187dd173e6552fe6
1  dbcc5a6c8b126e6be68b2bfb838d23ade8e7de57
2  889432c467b59475900845c1f414e0d3461d1459
3  7e3f69b71019b93123114375119d18df6a1f3a2a
4  4c2a8ed7374912ee6c980b29fe5021aa94f4c543

#### Now, we continue with download the datasets as well as submissions (could take awhile ~15-20 mins) to calculate the RMSE error.
#### Based on the error, we can calculate the challenge/competition scores
#### In order to calculate the reward, we also get individual participant's stake

In [3]:
# add errors, and challenge competition and stake scores

errors = {participant.address: val.compute_error(participant) for participant in participants}
df["error"] = df["address"].map(errors)

challenge_scores = val.compute_challenge_scores(challenge)
df["challenge_score"] = df["address"].map(challenge_scores)

competition_scores = [val.compute_competition_score(participant) for participant in participants]
df["competition_scores"] = competition_scores

stakes = val.get_stakes(challenge)
df["stake"] = df["address"].map(stakes)

df.head()

downloading file QmVtt8XrDJgd8kTYLieNEBSbwxfVLYqF5ssDFvJD4ZcKkL
downloading file QmSuceDqAkknSAU4R3HhLLPGN5tEkkmKUaThm3qMNPMgrJ
downloading file Qmaie1d2MuJQ3JxcgQ9mBnbryLqAjGgwoWo3DoLYagG9e3
downloading file Qme5fpHFY2Lzp9xQ82XM4FZEWQ8EmxmV5KYUccEni31nJ7
downloading file Qmd67RKQizYn34XvJGux8Dw76dHcRS4DDqhxK51Uy4WFBm
downloading file QmaZNrkzthGZJu5LCYxWU3QC1orrNiY3twTLJWCCJYpwJu
downloading file QmRZnDbMYJB1T5MQ8dVRMr7Fqi4MiZDiWP9pMp3XRwVY3H
downloading file QmRhv9hTm9W1rsPZq1TCFGbxovCRz3NR4SyhH1RSwVC1uz
downloading file QmNYuFEQRd7JmRyRQeQpTbWazo27UzaMg9A9XCeZLiWB8a
downloading file QmSJAtH595j681cyao1Nu5cRnpbgu5JR9vE9uXQnJau33H
downloading file QmRBwAzqo5dt4pG9qA5J4s17T7Ppuh2HSCr6kjBmodkNKx
downloading file QmVdmTZLNwz93Ri44Mfb1CkeWBakAVfcXRAJNNevTALwrF
downloading file QmbAyvpAspjd9GFGMaHCo6oVjg3Tm5Kb1DBx5W3227h8ZW
downloading file QmZ4aJ2JL2ATvYVfpvhB9eH6pDBoFbpW4AnSceo5ePJJ7y
downloading file QmRXLpuwjEZGf7uWYtvCAKokbj7kqyrLs6ce5R5x1dKK61
downloading file QmUUPkQFCSv27j7XzzDwSq97GrPqhLeFdGbg8yrZnvYgV2
downloading file QmfPdoPHd5M1AXnH4jRCGGNDTA7gLr2NbnfbJwAVmrT1FQ
downloading file Qmajpbj5vRLJ2ejVcsz9uJgQarQeDPJVvgBNpcB6Sv3GwQ
downloading file QmUhuEac8ADyNWUaaYL9Q8U5wM7vofUrEoBmFPkepBaQz8
downloading file QmULM6ouGMBVz9ATBycbBuNHjYwXzMHF81MLLCXx9heBkP
downloading file QmXKUAbSBosmM1tMqJYrjkpc9KZdmB74dihGVz16H83uGK
downloading file QmQCbpSQN5xnMAzcP54Yz7RUURypmQbGx4r8RDRft1LR7F
downloading file QmcWFoYVvyTaJUeNbL9dfndtTKoRqMdkvT6VgpiUqHLoNQ
downloading file QmZpaeXxRnWjKCKWasfUj1Le2qnA694Pi62EQFMqM4nhWY
downloading file QmUnnkbcNDTQCi53eiV1T3Ec3NjbLGhbQ6gGRVwgtNvvDV
downloading file QmeYhjZ7Z4PQtaAF6ssZCkSAMc4uzNhiSKP63W9r8cvg3e
downloading file QmWAP7UYcc3ZrwawF3dtEbPX6ddLaG2sdZpTGAs1hK3GTp
scanning the Polygon blockchain
..........................................................................................................................................................................................
blockchain scan completed
downloading file QmZteoVtw4bPTLLjQE4x6gHLgHuHBET9d1JX7CtVqWCsKA
downloading file Qme4EwAWYSkamc8LUp6qBSt18bQ4UnMHLMA4cazmhRQLnc
downloading file QmePJ2nJuTrKZw28VGPBoZ8VRcWdKFRVqa8nhLGcroMa8z
downloading file Qmchxf1fZyLZo78pLBDHwNBphHe5VWhPmid1vGWeUv6qRm
downloading file QmbZXYkfkCCUGPf1eqrh7J88PSVpuapH7pSon6iGfHMkHP
downloading file QmPvZB3mM1ZttJ1MizekiqXi5ZnWHgSWGzYFeT8Co2JGNX
downloading file Qmdo4hXASj2b74oBX4wFYhEBtVRWLXKDEWEf7Vo2gf8yuT
downloading file QmYBKCugk2vnHAbofStpF4cQuHq98hRP3PjMWSG18V6Vzn
downloading file QmeeNKzKAayj7LJAi47cXV9raZB8KtZmNnBSvkukWwELQQ
downloading file QmUeii6ZCE2vBU8GY94K2RK3e3zZYRc5esqF3eTW42CfuT
downloading file QmTCupnsa9MGHzDhyGkrDGb6qQEApzYu8XMcJGLaKDztSz
downloading file Qmddp3FSed7JSEZVQWvX19S9CzJLtAJx2BntWJhWUXiyoC
downloading file Qmf7gJhGHAv3U7qDxZKCp3nJQCy2N5VfXmHqabSyHcniEG
downloading file QmXds48ky9HagBtuV3A6Ceby67JQ9BzNRWXNoRp5CQQAmC
downloading file QmP2y48tyD61zaj2tQD4hVtGMuxJLtMiSNoz7Ldea2vNqM
downloading file QmbkqriAhqKmVVXDKSf5j3werdB3QLcbDMX45rEq5oT7Q3
downloading file QmWVyruuf24T8aUsYDHEDiXAStP1hvyrZP2V6NJ3JWKEQv
downloading file QmQjAwMzWPonyQH3j151MscXnTkiwz8aB1BJDyuppd2Lq3
downloading file QmWWD9yR4kgazWytdwRJ3GTjR17yHQ6gD5BkxWxcrj9PWb

,address,error,challenge_score,competition_scores,stake
0,16391fe372c2f5b2a3874e65187dd173e6552fe6,NaN,NaN,NaN,1084.000000000000000000
1,dbcc5a6c8b126e6be68b2bfb838d23ade8e7de57,0.390718,0.000000,0.333333,2539.163043478199995206
2,889432c467b59475900845c1f414e0d3461d1459,0.372331,0.045455,0.000000,1084.000000000000000000
3,7e3f69b71019b93123114375119d18df6a1f3a2a,0.348715,0.227273,0.144242,1084.000000000000000000
4,4c2a8ed7374912ee6c980b29fe5021aa94f4c543,0.321309,0.272727,0.122424,1084.000000000000000000

#### Calculates the rewards (challenge, competition, stake) for the defined challenge number
#### The displayed result can be compared to the 'My Scores' and/or 'Leaderboard' published on DApp (https://competition.rocketcapital.ai/)

In [4]:
# add challenge, competition, stake and total rewards

challenge_rewards = val.compute_challenge_rewards(challenge)
df["challenge_reward"] = df["address"].map(challenge_rewards)

competition_rewards = val.compute_competition_rewards(challenge)
df["competition_reward"] = df["address"].map(competition_rewards)

stake_rewards = val.compute_stake_rewards(challenge)
df["stake_reward"] = df["address"].map(stake_rewards)

df["total_reward"] = df.challenge_reward + df.competition_reward + df.stake_reward
df

,address,error,challenge_score,competition_scores,stake,challenge_reward,competition_reward,stake_reward,total_reward
0,16391fe372c2f5b2a3874e65187dd173e6552fe6,NaN,NaN,NaN,1084.000000000000000000,0,0,25.2710106073,25.2710106073
1,dbcc5a6c8b126e6be68b2bfb838d23ade8e7de57,0.390718,0.000000,0.333333,2539.163043478199995206,0,0,59.1948488979,59.1948488979
2,889432c467b59475900845c1f414e0d3461d1459,0.372331,0.045455,0.000000,1084.000000000000000000,0,0,25.2710106073,25.2710106073
3,7e3f69b71019b93123114375119d18df6a1f3a2a,0.348715,0.227273,0.144242,1084.000000000000000000,0,0,25.2710106073,25.2710106073
4,4c2a8ed7374912ee6c980b29fe5021aa94f4c543,0.321309,0.272727,0.122424,1084.000000000000000000,2.3529411764,0,25.2710106073,27.6239517837
5,b7ece21c962697a3194c0b6e4b81db54433055ab,0.288585,0.818182,0.420606,1090.086956521700000344,58.8235294117,30.909090909,25.4129142445,115.1455345652
6,a16a483a18f00a00b14b93438e8ad21f485b382f,0.290025,0.545455,0.431515,1163.130434782600005405,30.5882352941,92.7272727272,27.1157578921,150.4312659134
7,fe3c3f351e6df846566e10119e4295ed69b2cd72,0.289977,0.590909,0.527879,1448.076086956400018834,35.294117647,154.5454545454,33.7586219129,223.5981941053
8,f097ed117dd3930f1eeb91569a6a61b4c52744c8,0.289841,0.636364,0.427879,1138.782608695599996906,4E+1,61.8181818181,26.5481433429,128.3663251610
9,3e04d3e08ea54c34f721ac007107fe7a4bd957d5,0.290536,0.454545,0.315152,1114.434782608599999065,21.1764705882,0,25.9805287937,47.1569993819
10,1be48b2b7594fe7e47701bc7e7bb83beaf84ecc0,0.290108,0.500000,0.446667,1266.228260869400003229,25.8823529411,123.6363636363,29.5192507488,179.0379673262
11,fb8bc3433016a64a3b8aa23c0275afe7c20feb53,0.286216,0.909091,0.816970,2175.467391304300008414,68.2352941176,278.1818181818,50.7161065696,397.1332188690
12,eba5ba85f72e40a9f2b8782c2bd51ec31a5564da,0.284387,1.000000,0.893333,2357.315217391299995597,77.6470588235,3.4E+2,54.9554777338,472.6025365573
13,e14867e41410bd7232a52b9400476c08b4e535b3,0.288672,0.772727,0.682424,1811.771739130299948782,54.1176470588,216.3636363636,42.2373642413,312.7186476637
14,98e41d65e981a882afcb05d41939197da3465b6f,0.288782,0.727273,0.689697,1993.619565217299992809,49.4117647058,247.2727272727,46.4767354054,343.1612273839
15,8355b0536a6a3b0116374b33dc3f8b7c344ca8bb,0.348715,0.181818,0.081818,1000.000000000000000000,0,0,23.3127404126,23.3127404126
16,2547002b0b8bfd052111981ef314118b6b54f61c,0.289264,0.681818,0.606061,1629.923913043300018443,44.7058823529,185.4545454545,37.9979930771,268.1584208845
17,bf72960a4051d7f0a3fb4dae1e1c1d3085567cb6,NaN,NaN,NaN,1084.000000000000000000,0,0,25.2710106073,25.2710106073
18,3ab42b6c81443da2e1f13e0a7d0150416620bf7c,0.348715,0.090909,0.000000,1084.000000000000000000,0,0,25.2710106073,25.2710106073
19,396d3b38be7269b2707f7a4feffae71cba4bb110,0.286487,0.863636,0.278788,1084.000000000000000000,63.5294117647,0,25.2710106073,88.8004223720
20,df5e0604fc23ac5df98a9ab7a62425ec2bd4b9d3,NaN,NaN,NaN,1000.000000000000000000,0,0,23.3127404126,23.3127404126
21,29174f88e6e60f48717624381d2bba019e4d0858,0.292214,0.409091,0.309091,1000.000000000000000000,16.4705882352,0,23.3127404126,39.7833286478
22,f8d50e3283fb6bf41260f7f294a48587d2a9b1fa,0.285116,0.954545,0.854545,1000.000000000000000000,72.9411764706,309.0909090909,23.3127404126,405.3448259741
23,af26322c7c7a3278d572a2f9bdac1a89c7b45b17,0.295903,0.363636,0.263636,1000.000000000000000000,11.7647058823,0,23.3127404126,35.0774462949
24,fe00eb2ef14f6bb4262bd40ba51fe39dd3166b42,0.348715,0.136364,0.036364,1000.000000000000000000,0,0,23.3127404126,23.3127404126
25,756ef834ecc631b289ef489408276b1d1f6479bd,0.319586,0.318182,0.218182,1000.000000000000000000,7.0588235294,0,23.3127404126,30.3715639420